version: '3.3'

services:
  backend:
    build: ./backend
    ports:
      - "5050:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
